# Generated by Django 5.2.11 on 2026-02-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='trusted_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='password_secret_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='username',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
