# Generated by Django 5.2.11 on 2026-03-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='default_schema',
            field=models.CharField(blank=True, default='dbo', help_text='Default schema used for unqualified table resolution (SQL Server default: dbo).', max_length=128),
        ),
        migrations.AddField(
            model_name='databaseconfig',
            name='schema_filter',
            field=models.CharField(blank=True, default='', help_text='When set, the schema explorer only shows tables belonging to this schema.', max_length=128),
        ),
    ]
