# Generated by Django 5.2.11 on 2026-02-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_trusted_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
